### ISSUE TITLE
Facer sistema de vidas e a reducción de estas.

### ISSUE THREAD

**Issue by ferreiroxabi** [Pacais/Practica1PRIAGrupo2#1]
- Sistema de vidas que se reducen ao golpear obstáculos
- Game over ao chegar a cero

**Comment by JoseChain93** [comment]
Buenos días, ya he creado los scripts de comportamiento de juego para establecer el sistema de vidas, restarlas, pero según estuve viendo pues hay dos formas de implementarlo así que he creado dos versiones, para las cúales a continuación voy a describirte las diferencias :

-La primera forma sería estableciendo ese comportamiento establecido a nivel de juego en el gamemanager y hacer la llamada al método declarando una variable para llamarlo.

-La segunda variable sería establecer ese comportamiento a nivel de personaje, lo cúal haría mas simple y sencillo su implementación al afectar directamente al personaje.

Cualquiera de las dos es viable pero puede influir posteriormente a la forma que tendremos de implementar el sistema de objetos que recuperen vida, así que se podrían crear dos ramas para cada una de ellas para ver que tal se desenvuelven en la práctica a la hora de implementar posteriormente mejoras o más extras al juego. 

Lo que he preparado de manera provisional de forma que interacturaría con la idea de que una UI que muestre las vidas, así que me quedaría saber como quereís enfocar ese tema a posteriores, de todas formas, en breves procederé a examinar la versión actual del proyecto y ajustar lo que ya he creado a esta. 

Un saludo

**Comment by Pacais** [comment]
Finalizado
