### ISSUE TITLE
Implementar "Power ups" que aumenten as vidas do personaxe

### ISSUE THREAD

**Issue by ferreiroxabi** [Pacais/Practica1PRIAGrupo2#2]
- Objetos spawneables que ao recollelos aumenten o número de vidas

**Comment by JoseChain93** [comment]
Esto lo tengo casi listo, cuando acabe de implementar el sistema de vidas, meteré este y realizare unas pruebas para comprobar su funcionamiento. Para llevar a cabo esta implementación sería necesario crear un script que haga que determinados objetos, al realizar una colisión con él y que realice un efecto de trigger al colisionar con el personaje, en el que haga una llamada al método de aumentar y disminuir vidas y que la aumente a una y destruya el objeto para que desapararezca

Luego sería incorporar este script de comportamiento al objeto que queremos que cure cada vez que se produzca este objeto y ya estaría funcionando.
