### ISSUE TITLE
Problema ca versión de Unity

### ISSUE THREAD

**Issue by Pacais** [Pacais/Practica1PRIAGrupo2#3]
Sospeito que a versión de Unity non é a adecuada, ao importar o proxecto o editor pideme que descargue a versión 6.0 así que temos que refacer o proxecto na versión 2022.3.45f1

**Comment by ferreiroxabi** [comment]
Xa se recreou o proxecto na versión 2022.3.45f1. Cerro a issue pois o proxecto xa funciona correctamente.
