### ISSUE TITLE
Traballo a Realizar semana 2

### ISSUE THREAD

**Issue by Pacais** [Pacais/Practica1PRIAGrupo2#8]
## Creación do personaxe, un pequeno diseño algo mellor ca un cubo
Diseño do fondo

**Comment by JoseChain93** [comment]
## Creación do sistema de vidas e que o xogo pare se tocas un obstáculo
Acabo de crear y una versión del proyecto con todo esto implementado y subido a un branch, un saludo.

**Comment by Elbafdez** [comment]
## Fixar a potencia de salto nunha variable
Fixen unha variable para a potencia de salto e modifiquei a forza de salto e a masa do xogador.

**Comment by Pacais** [comment]
Traballo realizado con éxito
